# Generated by Django 2.0 on 2020-02-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='发表时间')),
                ('Text', models.TextField(max_length=12, verbose_name='评论内容')),
                ('Form_uid', models.CharField(max_length=20, verbose_name='评论用户')),
                ('to_uid', models.CharField(max_length=20, verbose_name='被评论用户')),
            ],
        ),
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendid', models.CharField(max_length=20, verbose_name='朋友')),
            ],
        ),
        migrations.CreateModel(
            name='matchmaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('tele', models.CharField(max_length=12, verbose_name='电话')),
                ('live', models.CharField(max_length=50, verbose_name='所在地')),
                ('emile', models.CharField(max_length=20, verbose_name='邮箱')),
                ('status', models.BooleanField(max_length=20, verbose_name='在线状态')),
            ],
        ),
        migrations.CreateModel(
            name='memberprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('people', models.CharField(max_length=20, verbose_name='设定人')),
            ],
        ),
        migrations.CreateModel(
            name='partyapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='活动时间')),
                ('place', models.CharField(max_length=20, verbose_name='活动地点')),
                ('tele', models.CharField(max_length=12, verbose_name='联系电话')),
                ('activities', models.TextField(max_length=12, verbose_name='内容介绍')),
                ('money', models.IntegerField(verbose_name='资金/每人')),
                ('Count', models.IntegerField(verbose_name='参与人数')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.matchmaker', verbose_name='举办人')),
            ],
        ),
        migrations.CreateModel(
            name='partymessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele', models.CharField(max_length=12, verbose_name='联系电话')),
                ('evaluate', models.TextField(max_length=12, verbose_name='活动评价')),
            ],
        ),
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=20, verbose_name='图片')),
                ('count', models.IntegerField(verbose_name='测试人数')),
                ('subject', models.CharField(max_length=20, verbose_name='标题')),
                ('http', models.TextField(max_length=20, verbose_name='测试连接')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('type', models.CharField(max_length=20, verbose_name='用户类型')),
                ('tele', models.CharField(max_length=12, verbose_name='电话')),
                ('live', models.CharField(max_length=50, verbose_name='所在地')),
                ('emile', models.CharField(max_length=20, verbose_name='邮箱')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('charater', models.CharField(max_length=50, verbose_name='自我介绍')),
                ('profession', models.CharField(max_length=20, verbose_name='职业')),
                ('photo', models.CharField(max_length=20, verbose_name='个人照片')),
                ('WXchart', models.CharField(max_length=20, verbose_name='微信')),
                ('friendcount', models.IntegerField(verbose_name='好友数')),
                ('sex', models.CharField(max_length=12, verbose_name='性别')),
                ('money', models.IntegerField(verbose_name='月薪')),
                ('education', models.CharField(max_length=12, verbose_name='学历')),
                ('marriage', models.CharField(max_length=12, verbose_name='婚姻状况')),
                ('status', models.BooleanField(max_length=20, verbose_name='在线状态')),
            ],
        ),
        migrations.CreateModel(
            name='userdynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('text', models.TextField(max_length=12, verbose_name='发表内容')),
                ('img', models.CharField(max_length=20, verbose_name='图片')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.user', verbose_name='用户号')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='邮箱')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
            ],
        ),
        migrations.CreateModel(
            name='xinwen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=20, verbose_name='文章标题')),
                ('subject', models.TextField(max_length=300, verbose_name='内容')),
                ('count', models.IntegerField(verbose_name='浏览次数')),
                ('day', models.DateField(verbose_name='发表时间')),
            ],
        ),
        migrations.AddField(
            model_name='partymessage',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.user', verbose_name='参与人'),
        ),
        migrations.AddField(
            model_name='partymessage',
            name='partyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.partyapply', verbose_name='活动编号'),
        ),
        migrations.AddField(
            model_name='friends',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.user', verbose_name='用户号'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.userdynamic', verbose_name='动态编号'),
        ),
    ]
