# Generated by Django 2.0 on 2020-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='邮箱验证码')),
                ('email', models.CharField(max_length=100, verbose_name='验证码邮箱')),
                ('sendtype', models.IntegerField(choices=[(1, 'register'), (2, 'forget'), (3, 'change')], verbose_name='验证码邮箱')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='charater',
            field=models.CharField(max_length=500, verbose_name='自我介绍'),
        ),
    ]
