# Generated by Django 2.0 on 2020-02-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20200214_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='WXchart',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='charater',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friendcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='好友数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='live',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marriage',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.IntegerField(blank=True, null=True, verbose_name='月薪'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='个人照片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职业'),
        ),
    ]
