# Generated by Django 2.0 on 2020-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20200314_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friendcount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='好友数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
