# Generated by Django 2.0 on 2020-03-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_auto_20200316_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='月薪'),
        ),
    ]
